#!/usr/bin/env python
import pycedar
import gzip
import pandas as pd
import logging
import matplotlib.pyplot as plt
import cProfile
import sys
import numpy as np
import os.path as osp
import os
import errno
import argparse
import yaml


#--------------------------------------------------#
#                                                  #
#                      MAIN                        #
#                                                  #
#--------------------------------------------------#

#load data

